name: Build LaTeX Report

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-report:
    runs-on: ubuntu-latest
    container: ghcr.io/matthew-mccall/dockerfiles/texlive:main
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PDF
        run: latexmk -interaction=nonstopmode main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: out/main.pdf
          if-no-files-found: error
